checks:
  go: true
build:
  nodes:
    analysis:
      environment:
        go:
          version: go1.14.7
      tests:
        override:
          - go-scrutinizer-run
    tests:
      project_setup:
        override: true
      environment:
        go:
          version: go1.14.7
      tests:
        override:
          - command: go test -coverprofile=c.out
            coverage:
              file: c.out
              format: go-cc
filter:
  excluded_paths:
    - "*_test.go"
