checks:
  go: true
build:
  environment:
    go:
      version: go1.14.7
  nodes:
    analysis:
      tests:
        override:
          - go-scrutinizer-run
    tests:
      project_setup:
        override: true
      tests:
        override:
          - command: go test -coverprofile=cover.out
            coverage:
              file: cover.out
              format: go-cc
filter:
  excluded_paths:
    - "*_test.go"
